version: '2'

services:
  yml-parser:
    image: cricd/parser-go
    restart: always
    environment:
      - EVENTAPI_IP=event-api
      - ENTITYSTORE_IP=entities
    volumes:
      - ./api/game-import:/games
    depends_on:
      - entities
      - eventstore
  entities:
    image: cricd/entities
    restart: always
    environment:
      - DB_HOST=entities-db
      - DB_PASSWORD=password # Override in production deployments
    ports:
      - "1337:1337"
    depends_on:
      - entities-db
  entities-db:
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=cricd-entities
      - MYSQL_PASSWORD=password # Override in production deployments
      - MYSQL_DATABASE=cricd-entities
      - MYSQL_ROOT_PASSWORD=password # Override in production deployments
    volumes:
      - ./api/entities-db:/var/lib/mysql
    ports:
      - "3306:3306"
  batting-processor:
    image: cricd/batting-processor
    restart: always
    environment:
      - DEBUG=*
    ports:
      - "3000:3000"
    depends_on:
      - eventstore-projections
  bowling-processor:
    image: cricd/bowling-processor
    restart: always
    environment:
      - DEBUG=*
    ports:
      - "3001:3001"
    depends_on:
      - eventstore-projections
  score-processor:
    image: cricd/score-processor
    restart: always
    environment:
      - DEBUG=*
    ports:
      - "3002:3002"
    depends_on:
      - eventstore-projections
  next-ball-processor:
    image: cricd/next-ball-processor
    restart: always
    environment:
      - DEBUG=*
    ports:
      - "3004:3004"
    depends_on:
      - eventstore-projections
      - entities
      - score-processor
  change-publisher:
    image: cricd/change-publisher
    restart: always
    ports:
      - "3100:3100"
    depends_on:
      - eventstore-projections
      - score-processor
  event-api:
    image: cricd/event-api
    restart: always
    ports:
      - "4567:4567"
    environment:
      - EVENTSTORE_IP=eventstore
      - NEXT_BALL_IP=next-ball-processor
    depends_on:
      - eventstore-projections
  eventstore-projections:
    build: ./api/eventstore-projections
    depends_on:
      - eventstore
  eventstore:
    image: eventstore/eventstore
    restart: always
    volumes:
      - ./api/eventstore-data:/var/lib/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
