version: '2'

services:
  event-service:
    image: ryankscott/cricd-eventservice
    restart: on-failure:10
    environment:
      - EVENTSTORE_IP=eventstore
    ports:
      - "4567:4567"
    depends_on:
      - eventstore
  entities:
    image: bradleyscott/cricd-entities
    restart: on-failure:10
    environment:
      - DB_HOST=entities-db
      - DB_PASSWORD=password # Override in production deployments
    ports:
      - "1337:1337"
    depends_on:
      - entities-db
  entities-db:
    image: postgres
    restart: on-failure:10
    environment:
      - POSTGRES_PASSWORD=password # Override in production deployments
      - POSTGRES_DB=cricd-entities
    ports:
      - "5432:5432"
  batsman-innings-processor:
    image: bradleyscott/cricd-batsman-innings-processor
    restart: on-failure:10
    ports:
      - "3000:3000"
    depends_on:
      - eventstore-projections
  bowler-match-processor:
    image: bradleyscott/cricd-bowler-match-processor
    restart: on-failure:10
    ports:
      - "3001:3001"
    depends_on:
      - eventstore-projections
  eventstore-projections:
    build: ./api/eventstore
    depends_on:
      - eventstore
  eventstore:
    image: adbrowne/eventstore
    restart: on-failure:10
    ports:
      - "2113:2113"
      - "1113:1113"
