version: '2'

services:
  event-service:
    image: ryankscott/cricd-eventservice
    restart: on-failure:10
    environment:
      - EVENTSTORE_IP=eventstore
    ports:
      - "4567:4567"
    depends_on:
      - eventstore
  entities:
    image: bradleyscott/cricd-entities
    restart: on-failure:10
    environment:
      - DB_HOST=entities-db
      - DB_PASSWORD=password # Override in production deployments
    ports:
      - "1337:1337"
    depends_on:
      - entities-db
  entities-db:
    image: mysql
    restart: on-failure:10
    environment:
      - MYSQL_USER=cricd-entities
      - MYSQL_PASSWORD=password # Override in production deployments
      - MYSQL_DATABASE=cricd-entities
      - MYSQL_ROOT_PASSWORD=password # Override in production deployments
    volumes:
      - ./api/entities-db:/var/lib/postgresql/data
    ports:
      - "3306:3306"
  batsman-innings-processor:
    image: bradleyscott/cricd-batsman-innings-processor
    restart: on-failure:10
    ports:
      - "3000:3000"
    depends_on:
      - eventstore-projections
  bowler-match-processor:
    image: bradleyscott/cricd-bowler-match-processor
    restart: on-failure:10
    ports:
      - "3001:3001"
    depends_on:
      - eventstore-projections
  eventstore-projections:
    build: ./api/eventstore-projections
    depends_on:
      - eventstore
  eventstore:
    image: eventstore/eventstore
    restart: on-failure:10
    volumes:
      - ./api/eventstore-data:/var/lib/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
